### ISSUE TITLE
Lua guide

### ISSUE THREAD

**Issue by s-m33r** [nalgeon/tryxinyminutes#3]
Currently working on a Lua guide. For now I'm porting over the guide from the `learnxinyminutes` page and breaking some of it into smaller sub-sections. After that I plan to go through some Lua primers/introduction and insert relevant text into the guide.

**Comment by nalgeon** [comment]
Great! It might be a good idea to send a PR while the guide is still in its early stages, so we can make sure that everything works out.

**Comment by s-m33r** [comment]
Sure! I'll finalise the 4 topics I have adapted and create a PR soon.
